---
- name: Install BDII
  package:
    name: htcondor-ce-bdii

- name: Configure BDII
  template:
    src: ce-bdii.conf.j2
    dest: /etc/condor-ce/config.d/06-ce-bdii.conf
  notify: reconfigure condor_ce

- name: Start BDII
  service:
    name: bdii
    state: started
    enabled: true
  register: service_bdii
