---
- src: geerlingguy.repo-epel
- src: git+https://gitlab.cern.ch/hephyvienna/ansible/role-grid.git
  name: hephyvienna.grid
- src: git+https://gitlab.cern.ch/hephyvienna/ansible/role-poolaccounts.git
  name: hephyvienna.poolaccounts
